name: Check dependent modules test integration

on: 
  repository_dispatch:
    types: [ tr_server ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - run: |
       echo ${{ github.event.client_payload.job_success }}
    - name: Check tr-server test execution success
      if: ${{ github.event.client_payload.job_success  == 'success' && github.event.client_payload.repo == 'Test_github_action' }}
      run: exit 0
    - name: Check tr-server test execution failure 
      if: ${{ github.event.client_payload.job_success  == 'failure' && github.event.client_payload.repo == 'Test_github_action' }}
      run: exit 1
  
