name: Check dependent modules test integration

on: 
  repository_dispatch:
    types: [ tr_server ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Check tr-server test execution success
      if: ${{ github.event.client_payload.job_success }} == 'success'
      run: exit 0
  
