# This is a basic workflow to help you get started with Actions

name: Create a tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs:
      tags:
        description: 'Enter Tag no'
        required: true
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createTag:
    name: "Create Tag"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Create a tag for release"
        run: |
          echo "done!"
          
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            console.log(context)
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ github.event.inputs.tags }}",
              sha: context.sha
            })
      - name: Create a release
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            console.log(context)
            github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ github.event.inputs.tags }}"
            })
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: slack-send
        # You may pin to the exact commit or the version.
        # uses: slackapi/slack-github-action@d5d276d7ae0f38f29322b80da9baf985cc80f8b1
        uses: slackapi/slack-github-action@v1.15.0
        with:
         payload: "{\"tag\": \"${{ github.event.inputs.tags }}\", \"GitDiff\": ${{steps.build_changelog.outputs.changelog}}}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
