# This is a basic workflow to help you get started with Actions

name: Create a tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs:
      tags:
        description: 'Enter Tag no'
        required: true
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createTag:
    name: "Create Tag"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            console.log(context)
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ github.event.inputs.tags }}",
              sha: context.sha
            })
      - name: Create a release
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            console.log(context)
            github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ github.event.inputs.tags }}"
            })
  findCommitDiff:
       name: "Find a difference between tags"
       runs-on: "ubuntu-latest"
       steps:
       - name: Git checkout
         uses: actions/checkout@v2
         with:
          fetch-depth: 0
       - name: Find previous Tag
         id: previousTag
         run: echo "::set-output name=previousTag::$(git tag --sort=-committerdate | head -2  | tail -1)"
       - name: find changes
         run: |
            echo "::set-output name=changeLog::$(git log '${{ steps.previousTag.outputs.previousTag }}'..'${{ github.event.inputs.tags }}' --pretty="%h - %s (%an)")"
         id: changeLog
       - name: print Change Log
         run: |
            echo ${{steps.changeLog.outputs.changeLog}}
         
