# This is a basic workflow to help you get started with Actions

name: Create a tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs:
      tags:
        description: 'Enter Tag no'
        required: true
        default: ''
      environment:
        description: 'Create a tag for: staging/production'
        required: true
        default: 'staging'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createTag:
    if: ${{ github.event.inputs.environment == 'staging' }}
    name: "Create Tag"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: 'develop'
        
      - name: setup git config
        run: |
          echo "creating tag from develop branch to deploy"
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "CI/CD"
          git config user.email "<>"
      - name: create a tag
        run: |
          git tag ${{ github.event.inputs.tags }}
          git push origin --tags

      - name: Create a release
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            console.log(context)
            github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ github.event.inputs.tags }}",
              prerelease: true
            })
  createTag-production:
    if: ${{ github.event.inputs.environment == 'production' }}
    name: "Create a Tag"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'
        
      - name: setup git config
        run: |
          echo "creating tag from develop branch"
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "CI/CD"
          git config user.email "<>"
      - name: create a tag
        run: |
          git tag ${{ github.event.inputs.tags }}
          git push origin --tags

      - name: Create a release
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            console.log(context)
            github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ github.event.inputs.tags }}"
            })
