# This is a basic workflow to help you get started with Actions

name: Deploy a tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs:
      tags:
        description: 'Enter Tag no to merge & deploy the changes'
        required: true
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-release:
    name: "deploy Release"
    runs-on: "ubuntu-latest"

    steps:
      # ... 
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Merge tag into a branch
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            console.log(context)
            github.repos.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: "${{ steps.extract_branch.outputs.branch }}",
              head: "${{ github.event.inputs.tags }}"
            })
      - name: Checkout
        uses: actions/checkout@v1
      
      


