# This is a basic workflow to help you get started with Actions

name: Deploy a tag to Staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs:
      tags:
        description: 'Enter Tag no to merge & deploy the changes'
        required: true
        default: ''
env:
 ENVIRONMENT: 'test'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-release:
    name: "deploy Release"
    runs-on: "ubuntu-latest"

    steps:
      # ... 
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Merge tag into a branch
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            console.log(context)
            github.repos.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: "master",
              head: "${{ github.event.inputs.tags }}"
            })
      - name: Checkout
        uses: actions/checkout@v1
      - name: gihub context
        run: echo ${{ env.ENVIRONMENT }}
      - run: |
 
         echo ${{ github.context.env.github_repository }}
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          channel-id: 'githubaction'  # Slack channel id to post message
          slack-message: 'Tag: ${{ github.event.inputs.tags }} for ${{ env.ENVIRONMENT }} has been deployed successfully'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo Changelog
        run: echo ${{steps.changelog.outputs.changelog}
      
#       - name: setup Node environment
#         uses: actions/setup-node@v1
#       - run: npm install
#       - run: npm run build
#       - name: List build folder
#         shell: bash
#         run: ls -l
      
      
      


