name: 'Send notification to Slack'
on:
  release:
    types:
      - published

jobs:
  release:
#     if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Build Changelog
        id: changelog
        run: |
         echo ${{ github.event }}
      - uses: actions/checkout@v1
      - name: Slack Notification
        uses: ./slack_notify
        with:
           job-status: ${{ job.status }}
           slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
           channel: devops
#         uses: rtCamp/action-slack-notify@v2
#         env:
#            SLACK_WEBHOOK: ${{ secrets.SLACK_TOKEN }}
#            SLACK_CHANNEL: githubaction
#            SLACK_TITLE: New Release has been created
#            SLACK_MESSAGE: 'Kindly review the release\n Run deploy a tag worfkflow to deploy the latest change. ${{ github.event.html_url }}'


