name: Deploy to development

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]
  workflow_dispatch:
      
      
env:
  ENVIRONMENT: development
defaults:
  run:
    shell: bash


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy-to-development:
    name: "deploy to development"
    runs-on: "ubuntu-latest"
    steps:
      # ... 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cat 
        run: |
         cat README.md
  
